spring.application.name=DailyMotionMiner

server.port=8081
// Se pone el /videos porque todos los datos se acceden a través de los videos, y así no hay que ponerlo en cada consulta.
dailymotion.url = https://api.dailymotion.com

